# Documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  - darwin
  - windows
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
